application:
  module: demo # 模块名称
  formatted-version: PongSky ${application.name}-${application.module} ${application.version} # 格式化版本
spring:
  application:
    name: ${application.name}-${application.module} # 应用名称
logging:
  config: classpath:logback-${spring.profiles.active}.xml # 指定 logback 路径
server:
  port: 10003 # 服务端口号