application:
  module: gateway # 模块名称
  formatted-version: PongSky ${application.name}-${application.module} ${application.version} # 格式化版本
spring:
  application:
    name: ${application.name}-${application.module} # 应用名称
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 利用服务名进行路由
      routes:
        - id: cloud-demo # 路由唯一ID
          uri: lb://cloud-demo # 路由到 cloud-demo 微服务
          predicates:
            - Path=/cloud-demo/** # 匹配以 /cloud-demo 开头的请求
          filters:
            - StripPrefix=1 # 去除 URL 开头的 /cloud-demo
        - id: cloud-payment # 路由唯一ID
          uri: lb://cloud-payment # 路由到 cloud-payment 微服务
          predicates:
            - Path=/cloud-payment/** # 匹配以 /cloud-payment 开头的请求
          filters:
            - StripPrefix=1 # 去除 URL 开头的 /cloud-payment
        - id: cloud-user # 路由唯一ID
          uri: lb://cloud-user # 路由到 cloud-user 微服务
          predicates:
            - Path=/cloud-user/** # 匹配以 /cloud-user 开头的请求
          filters:
            - StripPrefix=1 # 去除 URL 开头的 /cloud-user
logging:
  config: classpath:logback-${spring.profiles.active}.xml # 指定 logback 路径
server:
  port: 10004 # 服务端口号